version: 2.1

macosBuildDefaults: &macosBuildDefaults
  macos:
      xcode: 12.3.0

linuxBuildDefaults: &linuxBuildDefaults
  docker:
    - image: conanio/gcc9:latest

commands:
  install_macos_build_tools:
    steps:
      - run:
          name: Install conan and build tools
          command: |
            brew install conan cmake pkg-config

  build_recipe:
    parameters:
      cliParams:
        default: ""
        type: string
    steps:
      - run:
          name: Build conan recipe
          command: |
            conan create . proofofwork/stable << parameters.cliParams >>

  setup_conan_remote:
    steps:
      - run:
          name: Setup conan remote
          command: |
            conan remote add proofofwork https://pow.jfrog.io/artifactory/api/conan/proofofwork
            conan user -p $CONAN_PASSWORD -r proofofwork $CONAN_USERNAME

  upload_conan_package:
    steps:
      - run:
          name: Upload conan package
          command: |
            conan upload data/${CIRCLE_TAG:1}@proofofwork/stable --all -r proofofwork --confirm

  build_macos:
    steps:
      - install_macos_build_tools
      - checkout
      - setup_conan_remote
      - build_recipe

  build_linux:
    steps:
      - checkout
      - setup_conan_remote
      - build_recipe:
          cliParams: "-s compiler.libcxx=libstdc++11"

jobs:

  build_macos:
    <<: *macosBuildDefaults
    steps:
      - build_macos

  release_macos:
    <<: *macosBuildDefaults
    steps:
      - build_macos
      - upload_conan_package

  build_linux:
    <<: *linuxBuildDefaults
    steps:
      - build_linux

  release_linux:
    <<: *linuxBuildDefaults
    steps:
      - build_linux
      - upload_conan_package

workflows:
  build-and-release:
    jobs:
      - build_linux:
          filters:
            tags:
              only: /^v.*/
      - build_macos:
          filters:
            tags:
              only: /^v.*/
      - release_macos:
          requires:
            - build_macos
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release_linux:
          requires:
            - build_linux
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
