version: 2.1

macos1230BuildDefaults: &macos1230BuildDefaults
  macos:
      xcode: 12.3.0
  environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      MACOS_BUILD: 1

macos1170BuildDefaults: &macos1170BuildDefaults
  macos:
      xcode: 11.7.0
  environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      MACOS_BUILD: 1

linuxBuildDefaults: &linuxBuildDefaults
  docker:
    - image: conanio/gcc9:latest

commands:
  install_macos_build_tools:
    steps:
      - run:
          name: Install conan and build tools
          command: |
            brew install pyenv cmake pkg-config
            eval "$(pyenv init -)"
            pyenv install 3.9.0
            pyenv global 3.9.0
            pip install conan

  build_recipe:
    parameters:
      cliParams:
        default: ""
        type: string
    steps:
      - run:
          name: Build conan recipe
          command: |
            [[ -n $MACOS_BUILD ]] && eval "$(pyenv init -)"
            conan create . proofofwork/stable << parameters.cliParams >>

  setup_conan_remote:
    steps:
      - run:
          name: Setup conan remote
          command: |
            [[ -n $MACOS_BUILD ]] && eval "$(pyenv init -)"
            conan remote add proofofwork https://pow.jfrog.io/artifactory/api/conan/proofofwork
            conan user -p $CONAN_PASSWORD -r proofofwork $CONAN_USERNAME

  upload_conan_package:
    steps:
      - run:
          name: Upload conan package
          command: |
            [[ -n $MACOS_BUILD ]] && eval "$(pyenv init -)"
            conan upload data/${CIRCLE_TAG:1}@proofofwork/stable --all -r proofofwork --confirm

  build_macos:
    steps:
      - install_macos_build_tools
      - checkout
      - setup_conan_remote
      - build_recipe

  build_linux:
    steps:
      - checkout
      - setup_conan_remote
      - build_recipe:
          cliParams: "-s compiler.libcxx=libstdc++11"

jobs:

  build_macos_1230:
    <<: *macos1230BuildDefaults
    steps:
      - build_macos

  build_macos_1170:
    <<: *macos1170BuildDefaults
    steps:
      - build_macos

  release_macos_1230:
    <<: *macos1230BuildDefaults
    steps:
      - build_macos
      - upload_conan_package

  release_macos_1170:
    <<: *macos1170BuildDefaults
    steps:
      - build_macos
      - upload_conan_package

  build_linux:
    <<: *linuxBuildDefaults
    steps:
      - build_linux

  release_linux:
    <<: *linuxBuildDefaults
    steps:
      - build_linux
      - upload_conan_package

workflows:
  build-and-release:
    jobs:
      - build_linux:
          filters:
            tags:
              only: /^v.*/
      - build_macos_1230:
          filters:
            tags:
              only: /^v.*/
      - build_macos_1170:
          filters:
            tags:
              only: /^v.*/
      - release_macos_1230:
          requires:
            - build_macos_1230
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release_macos_1170:
          requires:
            - build_macos_1170
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - release_linux:
          requires:
            - build_linux
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
