name: Stable Builds
on:
  push:
    branches:
      - production
env:
  BUILD_TYPE: Release
jobs:
  prep:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
    outputs:
      releaseVersion: ${{ steps.release.outputs.tag_name }}
