name: Test Commit
on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened]
    branches:
      - 'production'
      - 'main'
env:
  BUILD_TYPE: Release
jobs:
  test:
    name: Test Data
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -f Dockerfile.test -t test .
      - name: Run Docker tests
        run: docker run test
